### ISSUE TITLE
First query performance issues

### ISSUE THREAD

**Issue by valencik** [cozydev-pink/protosearch#79]
The first search is quite slow in browser

![image](https://github.com/cozydev-pink/protosearch/assets/5440389/665fbe27-090b-4b8d-b011-833485fdb3b1)

![image](https://github.com/cozydev-pink/protosearch/assets/5440389/d51cf5a9-a8da-49b0-a5fc-fc36d0ae3880)

**Comment by armanbilge** [comment]
I'll explore running the search in a worker! This will be the eventual architecture anyway when we compile to WASM.

**Comment by armanbilge** [comment]
Forgot to mention this issue in https://github.com/cozydev-pink/protosearch/pull/82 😇

**Comment by valencik** [comment]
I think we can close this as completed in #82
The UX is way better now is likely a lot closer to the real setup as Arman as pointed out.
